version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nodipar
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    command: npm run dev
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nodipar?schema=public
      PORT: 4000
      NODE_ENV: development
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/package.json:/app/package.json
      - ./backend/node_modules:/app/node_modules
    ports:
      - '4000:4000'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host
    environment:
      VITE_API_BASE_URL: http://localhost:4000/api
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tsconfig.node.json:/app/tsconfig.node.json
      - ./frontend/package.json:/app/package.json
      - ./frontend/node_modules:/app/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  postgres-data:
